services:
  - type: web
    name: telegram-bot
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WH_SECRET
        value: secret123
    healthCheckPath: /
